#!/bin/bash

# run:
# cp hooks/pre-commit .git/hooks/pre-commit

source "$(dirname "$0")/../../hooks/version-bump.sh"

bump_version "$(dirname "$0")/../../" "styles.css" "index.html"
bump_version "$(dirname "$0")/../../" "scripts.js" "index.html"
